import { X } from 'lucide-react'
import { useState } from 'react'
import { emptyLecture, timetableDays } from '../../data/mock/timetable'

function Field({ label, name, value, onChange, type = 'text', required = true }) { return <label className="block text-sm font-semibold text-[var(--color-ink)]">{label}<input required={required} type={type} name={name} value={value} onChange={onChange} className="mt-2 min-h-11 w-full rounded-xl border border-[#d8e5db] bg-[#fbfdfb] px-3 text-sm font-normal outline-none focus:border-[var(--color-accent)] focus:ring-2 focus:ring-[#cfe8d8]" /></label> }

export function AddLectureModal({ isOpen, defaultDay, onClose, onAdd }) {
  const [form, setForm] = useState({ ...emptyLecture, day: defaultDay })
  if (!isOpen) return null
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = (event) => { event.preventDefault(); onAdd({ ...form, id: Date.now() }); setForm({ ...emptyLecture, day: defaultDay }) }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#173e32]/35 p-0 sm:items-center sm:p-5"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-[#f8fbf8] p-5 shadow-2xl sm:max-w-lg sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-accent)]">New schedule item</p><h2 className="mt-1 text-2xl font-semibold text-[var(--color-ink)]">Add lecture</h2></div><button type="button" onClick={onClose} aria-label="Close add lecture form" className="grid size-10 place-items-center rounded-xl text-[var(--color-muted)] hover:bg-white"><X size={19} aria-hidden="true" /></button></div><form onSubmit={submit} className="mt-6 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Subject" name="subject" value={form.subject} onChange={update} /><Field label="Topic" name="topic" value={form.topic} onChange={update} /></div><label className="block text-sm font-semibold text-[var(--color-ink)]">Day<select name="day" value={form.day} onChange={update} className="mt-2 min-h-11 w-full rounded-xl border border-[#d8e5db] bg-[#fbfdfb] px-3 text-sm font-normal outline-none focus:border-[var(--color-accent)]">{timetableDays.map((day) => <option key={day}>{day}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><Field label="Start time" name="startTime" type="time" value={form.startTime} onChange={update} /><Field label="End time" name="endTime" type="time" value={form.endTime} onChange={update} /></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Room" name="room" value={form.room} onChange={update} /><Field label="Teacher" name="teacher" value={form.teacher} onChange={update} /></div><div className="flex gap-3 pt-2"><button type="button" onClick={onClose} className="min-h-11 flex-1 rounded-xl border border-[#d8e5db] text-sm font-bold text-[var(--color-muted)]">Cancel</button><button type="submit" className="min-h-11 flex-1 rounded-xl bg-[var(--color-accent)] text-sm font-bold text-white">Add Lecture</button></div></form></div></div>
}