import { AlertTriangle, Check, Circle, Clock3, Eye, Play } from 'lucide-react'
import { PriorityBadge } from './PriorityBadge'

const statusLabels = { pending: 'Not Started', 'in-progress': 'In Progress', completed: 'Completed', skipped: 'Skipped', overdue: 'Overdue' }
const statusIcons = { pending: Circle, 'in-progress': Play, completed: Check, skipped: Play, overdue: AlertTriangle }

export function StudyTaskCard({ task, onToggle, onSelect, onStart }) {
  const StatusIcon = statusIcons[task.status] ?? Circle
  return <article className={`dashboard-card 3d-hover bg-white p-4 sm:p-5 ${task.status === 'completed' ? 'opacity-75' : ''}`}><div className="flex items-start gap-3"><button type="button" onClick={() => onToggle(task.id)} aria-label={`Mark ${task.title} ${task.status === 'completed' ? 'not started' : 'complete'}`} aria-pressed={task.status === 'completed'} className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-full border active:scale-95 ${task.status === 'completed' ? 'border-[var(--color-accent)] bg-[var(--color-accent)] text-white' : 'border-[#c9d8cd] text-[var(--color-muted)]'}`}><StatusIcon size={15} strokeWidth={2.5} aria-hidden="true" /></button><button type="button" onClick={() => onSelect(task)} className="min-w-0 flex-1 text-left"><h3 className={`truncate text-sm font-semibold ${task.status === 'completed' ? 'text-[var(--color-muted)] line-through' : 'text-[var(--color-ink)]'}`}>{task.title}</h3><p className="mt-1 truncate text-xs text-[var(--color-muted)]">{task.subject} · {task.topic}</p><div className="mt-3 flex flex-wrap items-center gap-2 text-[11px] font-semibold text-[var(--color-muted)]"><span className="flex items-center gap-1"><Clock3 size={12} aria-hidden="true" /> {task.duration} min</span><span>{task.dueDate === 'today' ? 'Due today' : task.dueDate}</span><span className="capitalize">{task.type}</span></div></button><button type="button" onClick={() => onSelect(task)} aria-label={`View ${task.title} details`} className="grid size-10 shrink-0 place-items-center rounded-xl text-[var(--color-muted)] hover:bg-[#eef7f0] hover:text-[var(--color-accent)]"><Eye size={17} aria-hidden="true" /></button></div><div className="mt-3 flex items-center justify-between gap-2 border-t border-[#edf1ed] pt-3"><PriorityBadge priority={task.priority} /><span className={`text-[11px] font-bold ${task.status === 'overdue' ? 'text-[#a14d2e]' : 'text-[var(--color-muted)]'}`}>{statusLabels[task.status]}</span>{task.status !== 'completed' && <button type="button" onClick={() => onStart(task)} className="min-h-9 rounded-lg px-2 text-xs font-bold text-[var(--color-accent)] hover:bg-[#eef7f0]">Start</button>}</div></article>
}