import { X } from 'lucide-react'
import { useState } from 'react'

export function AddTopicSheet({ isOpen, topic, onClose, onSave }) {
  const [form, setForm] = useState(topic ?? { name: '', description: '', status: 'not-started', studyProgress: 0, quizAccuracy: 0, revisionStatus: 'pending' })
  if (!isOpen) return null
  const update = (event) => setForm((current) => ({ ...current, [event.target.name]: event.target.value }))
  const submit = (event) => { event.preventDefault(); onSave({ ...form, id: topic?.id ?? Date.now() }); setForm({ name: '', description: '', status: 'not-started', studyProgress: 0, quizAccuracy: 0, revisionStatus: 'pending' }) }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#173e32]/35 p-0 sm:items-center sm:p-5"><div className="w-full rounded-t-3xl bg-[#f8fbf8] p-5 shadow-2xl sm:max-w-lg sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-accent)]">Grow this subject</p><h2 className="mt-1 text-2xl font-semibold text-[var(--color-ink)]">{topic ? 'Edit topic' : 'Add topic'}</h2></div><button type="button" onClick={onClose} aria-label="Close topic form" className="grid size-10 place-items-center rounded-xl text-[var(--color-muted)] hover:bg-white"><X size={19} aria-hidden="true" /></button></div><form onSubmit={submit} className="mt-6 space-y-4"><label className="block text-sm font-semibold text-[var(--color-ink)]">Topic Name<input required name="name" value={form.name} onChange={update} className="mt-2 min-h-11 w-full rounded-xl border border-[#d8e5db] bg-white px-3 text-sm font-normal outline-none focus:border-[var(--color-accent)]" /></label><label className="block text-sm font-semibold text-[var(--color-ink)]">Description<textarea required name="description" value={form.description} onChange={update} rows="3" className="mt-2 w-full rounded-xl border border-[#d8e5db] bg-white px-3 py-3 text-sm font-normal outline-none focus:border-[var(--color-accent)]" /></label><div className="flex gap-3 pt-2"><button type="button" onClick={onClose} className="min-h-11 flex-1 rounded-xl border border-[#d8e5db] text-sm font-bold text-[var(--color-muted)]">Cancel</button><button type="submit" className="min-h-11 flex-1 rounded-xl bg-[var(--color-accent)] text-sm font-bold text-white">{topic ? 'Save Changes' : 'Add Topic'}</button></div></form></div></div>
}