import { ArrowUpRight, BookOpen, Pencil, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { getCompletedTopics, getSubjectProgress, getSubjectStatus, getWeakTopics } from '../../utils/subjects'
import { SubjectProgress } from './SubjectProgress'
import { SubjectStatusBadge } from './SubjectStatusBadge'

export function SubjectCard({ subject, onView, onEdit, onDelete }) {
  const [confirming, setConfirming] = useState(false)
  const progress = getSubjectProgress(subject)
  const weakTopics = getWeakTopics(subject)
  return <article className="dashboard-card 3d-hover bg-white p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-[#edf5ef] text-[var(--color-accent)]"><BookOpen size={20} aria-hidden="true" /></span><div className="min-w-0"><h2 className="truncate text-lg font-semibold text-[var(--color-ink)]">{subject.name}</h2><p className="mt-1 truncate text-xs text-[var(--color-muted)]">{subject.description}</p></div></div><SubjectStatusBadge status={getSubjectStatus(subject)} /></div><div className="mt-5"><SubjectProgress percentage={progress} /><div className="mt-3 flex justify-between gap-3 text-xs font-semibold text-[var(--color-muted)]"><span>{getCompletedTopics(subject)} / {subject.topics.length} topics completed</span><span>Attendance {subject.attendance}%</span></div></div>{weakTopics.length > 0 && <p className="mt-4 text-xs font-semibold text-[#9b7024]">{weakTopics.length} weak {weakTopics.length === 1 ? 'topic' : 'topics'} to revisit</p>}{confirming ? <div className="mt-4 rounded-xl bg-[#fff4ef] p-3"><p className="text-sm font-semibold text-[#8d4228]">Delete {subject.name}?</p><p className="mt-1 text-xs text-[#a14d2e]">All of its topics will be removed.</p><div className="mt-3 flex gap-2"><button type="button" onClick={() => setConfirming(false)} className="min-h-10 flex-1 rounded-xl border border-[#e6cfc6] text-xs font-bold text-[#8d4228]">Cancel</button><button type="button" onClick={() => onDelete(subject.id)} className="min-h-10 flex-1 rounded-xl bg-[#a14d2e] text-xs font-bold text-white">Delete</button></div></div> : <div className="mt-5 flex items-center justify-between border-t border-[#edf1ed] pt-3"><button type="button" onClick={() => onView(subject.id)} className="flex min-h-10 items-center gap-1 rounded-xl px-2 text-xs font-bold text-[var(--color-accent)] hover:bg-[#eef7f0]">View Topics <ArrowUpRight size={15} aria-hidden="true" /></button><div className="flex gap-1"><button type="button" onClick={() => onEdit(subject)} aria-label={`Edit ${subject.name}`} className="grid size-10 place-items-center rounded-xl text-[var(--color-muted)] hover:bg-[#eef7f0] hover:text-[var(--color-accent)]"><Pencil size={16} aria-hidden="true" /></button><button type="button" onClick={() => setConfirming(true)} aria-label={`Delete ${subject.name}`} className="grid size-10 place-items-center rounded-xl text-[var(--color-muted)] hover:bg-[#fff0eb] hover:text-[#a14d2e]"><Trash2 size={16} aria-hidden="true" /></button></div></div>}</article>
}