import { Pencil, Trash2 } from 'lucide-react'
import { useState } from 'react'
import { TopicStatusBadge } from './TopicStatusBadge'

const nextStatus = { 'not-started': 'in-progress', 'in-progress': 'completed', completed: 'not-started' }

export function TopicCard({ topic, onStatusChange, onEdit, onDelete }) {
  const [confirming, setConfirming] = useState(false)
  const displayedStatus = topic.quizAccuracy > 0 && topic.quizAccuracy < 60 ? 'needs-revision' : topic.status
  return <article className="rounded-2xl border border-[#e2ece4] bg-white p-4"><div className="flex items-start justify-between gap-3"><button type="button" onClick={() => onStatusChange(topic.id, nextStatus[topic.status])} className="flex min-w-0 flex-1 items-start gap-3 text-left active:scale-[0.99]"><span className={`mt-0.5 grid size-7 shrink-0 place-items-center rounded-full border ${topic.status === 'completed' ? 'border-[var(--color-accent)] bg-[var(--color-accent)] text-white' : 'border-[#c9d8cd] text-[var(--color-muted)]'}`}>{topic.status === 'completed' ? '✓' : '○'}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-[var(--color-ink)]">{topic.name}</span><span className="mt-1 block truncate text-xs text-[var(--color-muted)]">{topic.description}</span></span></button><TopicStatusBadge status={displayedStatus} /></div><div className="mt-4 flex items-center justify-between text-xs font-semibold text-[var(--color-muted)]"><span>Study progress</span><span>{topic.studyProgress}%</span></div><div className="mt-1.5 h-1.5 overflow-hidden rounded-full bg-[#e7efe9]"><div className="h-full rounded-full bg-[var(--color-accent)]" style={{ width: `${topic.studyProgress}%` }} /></div><div className="mt-3 flex items-center justify-between gap-3 text-[11px] text-[var(--color-muted)]"><span>Quiz accuracy: {topic.quizAccuracy || '—'}%</span><span>Revision: {topic.revisionStatus}</span></div>{confirming ? <div className="mt-3 rounded-xl bg-[#fff4ef] p-3"><p className="text-xs font-semibold text-[#8d4228]">Delete this topic?</p><div className="mt-2 flex gap-2"><button type="button" onClick={() => setConfirming(false)} className="min-h-9 flex-1 rounded-lg border border-[#e6cfc6] text-xs font-bold text-[#8d4228]">Cancel</button><button type="button" onClick={() => onDelete(topic.id)} className="min-h-9 flex-1 rounded-lg bg-[#a14d2e] text-xs font-bold text-white">Delete</button></div></div> : <div className="mt-3 flex justify-end gap-1"><button type="button" onClick={() => onEdit(topic)} aria-label={`Edit ${topic.name}`} className="grid size-9 place-items-center rounded-lg text-[var(--color-muted)] hover:bg-[#eef7f0] hover:text-[var(--color-accent)]"><Pencil size={15} aria-hidden="true" /></button><button type="button" onClick={() => setConfirming(true)} aria-label={`Delete ${topic.name}`} className="grid size-9 place-items-center rounded-lg text-[var(--color-muted)] hover:bg-[#fff0eb] hover:text-[#a14d2e]"><Trash2 size={15} aria-hidden="true" /></button></div>}</article>
}