import { Check, X } from 'lucide-react'
import { useState } from 'react'

export function CompleteRevisionSheet({ revision, nextDate, onClose, onSave }) {
  const [confidence, setConfidence] = useState('medium')
  const [understanding, setUnderstanding] = useState('yes')
  if (!revision) return null
  const submit = (event) => { event.preventDefault(); onSave({ confidence, understanding }) }
  return <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#173e32]/35 p-0 sm:items-center sm:p-5"><div className="max-h-[92vh] w-full overflow-y-auto rounded-t-3xl bg-[#f8fbf8] p-5 shadow-2xl sm:max-w-lg sm:rounded-3xl sm:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-accent)]">One last check-in</p><h2 className="mt-1 text-2xl font-semibold text-[var(--color-ink)]">Complete Revision</h2></div><button type="button" onClick={onClose} aria-label="Close completion form" className="grid size-10 place-items-center rounded-xl text-[var(--color-muted)] hover:bg-white"><X size={19} aria-hidden="true" /></button></div><p className="mt-5 text-sm font-semibold text-[var(--color-ink)]">How confident are you about {revision.topic}?</p><fieldset className="mt-3 space-y-2"><legend className="sr-only">Confidence level</legend>{['very-low', 'low', 'medium', 'high', 'very-high'].map((value) => <label key={value} className={`flex min-h-11 cursor-pointer items-center gap-3 rounded-xl border px-3 text-sm font-semibold capitalize ${confidence === value ? 'border-[var(--color-accent)] bg-[#e1f0e7] text-[var(--color-accent)]' : 'border-[#d8e5db] text-[var(--color-muted)]'}`}><input className="sr-only" type="radio" name="confidence" value={value} checked={confidence === value} onChange={(event) => setConfidence(event.target.value)} /><span className={`grid size-5 place-items-center rounded-full border ${confidence === value ? 'border-[var(--color-accent)]' : 'border-[#c9d8cd]'}`}>{confidence === value && <Check size={13} aria-hidden="true" />}</span>{value.replace('-', ' ')}</label>)}</fieldset><fieldset className="mt-5"><legend className="text-sm font-semibold text-[var(--color-ink)]">Did you understand the topic?</legend><div className="mt-2 grid grid-cols-3 gap-2">{['yes', 'partially', 'no'].map((value) => <label key={value} className={`flex min-h-11 cursor-pointer items-center justify-center rounded-xl border px-2 text-xs font-bold capitalize ${understanding === value ? 'border-[var(--color-accent)] bg-[#e1f0e7] text-[var(--color-accent)]' : 'border-[#d8e5db] text-[var(--color-muted)]'}`}><input className="sr-only" type="radio" name="understanding" value={value} checked={understanding === value} onChange={(event) => setUnderstanding(event.target.value)} />{value}</label>)}</div></fieldset><div className="mt-5 rounded-2xl bg-[#eaf3ed] p-4"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[var(--color-accent)]">Next revision</p><p className="mt-1 text-sm font-semibold text-[var(--color-ink)]">Revision #{revision.revisionNumber + 1} · {nextDate}</p></div><form onSubmit={submit}><button type="submit" className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[var(--color-accent)] text-sm font-bold text-white"><Check size={16} aria-hidden="true" /> Save Reflection</button></form></div></div>
}